/**
 * @vitest-environment node
 *
 * Integration tests for the mammoth library against synthetic DOCX fixtures.
 * Mirrors __tests__/api/pdf-parse.test.ts — verifies that real DOCX bytes
 * extract into text the rest of the pipeline can consume.
 *
 * Fixtures are generated by scripts/generate-docx-fixtures.ts and reproduce
 * three layouts found in real-world resumes: plain paragraphs, table-based
 * "Technical Proficiency" blocks, and Heading-styled sections with bullets.
 */
import { describe, it, expect } from 'vitest'
import { readFileSync } from 'fs'
import { resolve } from 'path'
import mammoth from 'mammoth'

const fixturesDir = resolve(__dirname, '../fixtures')

describe('mammoth integration', () => {
  it('extracts text from a plain single-column DOCX resume', async () => {
    const buffer = readFileSync(resolve(fixturesDir, 'sample-resume-plain.docx'))
    const { value, messages } = await mammoth.extractRawText({ buffer })

    expect(value.length).toBeGreaterThan(100)
    expect(value).toContain('JANE DOE')
    expect(value).toContain('jane.doe@example.com')
    expect(value).toContain('Profile Summary')
    expect(value).toContain('TypeScript')
    // Plain documents shouldn't trigger mammoth warnings.
    expect(messages).toEqual([])
  })

  it('flattens table-based key-value layouts into separate lines', async () => {
    const buffer = readFileSync(resolve(fixturesDir, 'sample-resume-table.docx'))
    const { value } = await mammoth.extractRawText({ buffer })

    expect(value).toContain('RAVI KUMAR')
    expect(value).toContain('Technical Proficiency')
    // The table cells (Languages | : | Java, Python, Go) flatten to consecutive
    // lines. We don't require any specific separator — only that all three
    // pieces survive into the extracted text so Gemini can stitch them back.
    expect(value).toContain('Languages')
    expect(value).toContain('Java, Python, Go')
    expect(value).toContain('Oracle, PostgreSQL, Redis')
  })

  it('extracts text from heading-styled DOCX with bulleted lists', async () => {
    const buffer = readFileSync(resolve(fixturesDir, 'sample-resume-heading.docx'))
    const { value } = await mammoth.extractRawText({ buffer })

    expect(value).toContain('PRIYA SHARMA')
    expect(value).toContain('Profile Summary')
    expect(value).toContain('Skills')
    // Bullet items are emitted as plain paragraphs by extractRawText (no `•`),
    // but the underlying text must still be present.
    expect(value).toContain('React, Vue, Svelte')
    expect(value).toContain('Built and maintained the company-wide component library.')
  })

  it('rejects a non-DOCX buffer with an error', async () => {
    const garbage = Buffer.from('not a docx file')
    await expect(mammoth.extractRawText({ buffer: garbage })).rejects.toBeDefined()
  })
})
